### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by evelope** [vuesion/vuesion#358] opened 2019-03-04 02:36 UTC
![image](https://user-images.githubusercontent.com/34190465/53707313-66481900-3e69-11e9-8e81-7510217f09cf.png)

**Comment by devCrossNet** [comment] 2019-03-04 08:05
can you provide a little bit more information?
Is it a freshly checked out project?

can you paste the output from running `./node_modules/.bin/vuesion --version`?

**Comment by jiaxings** [comment] 2019-03-08 00:45
Hi,Johannes
I got the same issue
![default](https://user-images.githubusercontent.com/8363200/53999458-681e1f00-417e-11e9-891b-d11d7dca2204.png)
os:windows
vuesion version is 1.0.2

**Comment by devCrossNet** [comment] 2019-03-08 05:36
hey @jiaxings,
thank you for the new information. The `cnpm` command is new to me, maybe it has something to do with this issue.

I am unfortunately not in front of a computer in the next couple of days but I will try to reproduce this behaviour as soon as possible on my machine. I don't have a windows machine, so I hope it is just something related to `cnpm`.

If I am not able to reproduce it, would you be able to allocate some time to help me troubleshooting this issue?

**Comment by jiaxings** [comment] 2019-03-08 07:53
sure, I will let you know if I find something.

**Comment by devCrossNet** [comment] 2019-03-18 19:41
@jiaxings @evelope I was not able to install the dependencies via cnpm, it takes ages and doesn't finish the node-sass installation. Therefore, I have no idea how to reproduce it.

Did you try it with `npm` instead of cnpm?

**Comment by devCrossNet** [comment] 2019-04-01 14:11
@evelope @jiaxings any news?

**Comment by OfficialFractal** [comment] 2019-04-04 15:01
I think I may have the same issue.

I'm new to all of this so I'm not entirely sure what's going on, but I fresh installed node.js, npm, cloned the git, ran npm install, and was greeted with this when trying to run npm run dev.

![InkedwZnl8wE_LI](https://user-images.githubusercontent.com/20522592/55566046-ebbd2400-56c8-11e9-9d0d-67a5a1f0749e.jpg)

**Comment by devCrossNet** [comment] 2019-04-04 15:14
@OfficialFractal do you also have windows running?

**Comment by OfficialFractal** [comment] 2019-04-04 18:53
@devCrossNet yep!  I'm on Windows 10 if that's what you're asking.

**Comment by devCrossNet** [comment] 2019-04-04 19:09
@OfficialFractal ok, let me try something. I will publish a new version of the vuesion/service. can you then install it and see if it's fixed?

**Comment by devCrossNet** [comment] 2019-04-04 19:21
@OfficialFractal `"@vuesion/service": "2.0.0-beta.2"` removes some process signal handlers. It's my first guess why this is not working on windows. please let me know if it fixes the issue.

reference: https://github.com/vuesion/packages/commit/0126278b3dade0c1e89a07f1acd812c80d42053f

**Comment by OfficialFractal** [comment] 2019-04-04 20:41
I deleted the vue-starter folder, updated npm, and tried again.  Here is the full result-

![latest try](https://user-images.githubusercontent.com/20522592/55586967-3c984100-56f8-11e9-9bdd-8fafce3d2b74.jpg)

Is there something specific I should try uninstalling before trying again?

**Comment by devCrossNet** [comment] 2019-04-04 21:18
You should update your package json to use the new version of the @vuesion/service and run npm install and then try again 🙂

**Comment by OfficialFractal** [comment] 2019-04-04 22:12
What package json should I be updating specifically?  Sorry for the ignorance!!

Just to clarify - before taking the last screenshot, I deleted _all_ of vue-starter, updated npm, re-downloaded vue-starter via git clone, then ran npm install and npm run dev.  That is the screenshot above.

Sorry for the misunderstanding and thanks for the time!!

**Comment by devCrossNet** [comment] 2019-04-05 07:49
@OfficialFractal no worries, let me give you a step by step instruction

- `git clone https://github.com/devCrossNet/vue-starter.git`
- `npm install`
- `npm install --save-dev @vuesion/service@2.0.0-beta.2`
- `./node_modules/.bin/vuesion --version` => should print `2.0.0-beta.2`, that means the update was successful
- `npm run dev`

If now the dev tasks works, we have it finally fixed 😊

**Comment by devCrossNet** [comment] 2019-04-05 14:35
@OfficialFractal if this error still exists it might be an issue with permissions. Exit code 2 stands for a permission problem. maybe this could help to solve it: https://github.com/zkat/npx/issues/146#issuecomment-384016791

**Comment by OfficialFractal** [comment] 2019-04-05 21:32
Very appreciated!  I tried everything you suggested in as many different orders and ways as I could think of but I get the same results.

<details>
  <summary>npm install</summary>

  ---

![npm install](https://user-images.githubusercontent.com/20522592/55657433-32de0e80-57c8-11e9-8d8c-3ecbe17367af.png)

  ---

</details>

<details>
  <summary>vuesion update</summary>

  ---

![Vuesion Update](https://user-images.githubusercontent.com/20522592/55657492-602abc80-57c8-11e9-8c2e-f8d4b61d7130.png)

  ---

</details>

<details>
  <summary>Error Log</summary>

  ---

![Error Log](https://user-images.githubusercontent.com/20522592/55657530-7f294e80-57c8-11e9-8cd5-645da86d2df8.png)

  ---

</details>

Maybe there's some insight to be gained in those results.  I wish I could be of more help!

**Comment by devCrossNet** [comment] 2019-04-05 21:36
@OfficialFractal thank you so much to spend so much time with me to figure out this issue.

**Comment by devCrossNet** [comment] 2019-04-05 21:49
I will try to install windows on my mac, maybe I get some more info if I run the vuesion/service in development mode

**Comment by devCrossNet** [comment] 2019-04-06 15:12
@OfficialFractal I git some new information:

<img width="1028" alt="Bildschirmfoto 2019-04-06 um 17 09 52" src="https://user-images.githubusercontent.com/1667598/55671296-0b05ae00-588f-11e9-96b2-5e145bd1566c.png">

so it's an issue with prettier! I think it's because of some git settings to convert LF to CTRLF, etc.

I will have a look if this is a known issue.

**Comment by devCrossNet** [comment] 2019-04-06 15:24
@OfficialFractal @evelope @jiaxings here is a section that could be helpful: https://prettier.io/docs/en/options.html#end-of-line

we need to decide if this should be part of the gitattributes!?

**Comment by devCrossNet** [comment] 2019-04-06 15:48
ok, so on windows you need to do the following:

- add `  "endOfLine": "lf"` to .prettierrc
- run `npm run prettier`
- run `npm run dev`

<img width="1028" alt="Bildschirmfoto 2019-04-06 um 17 47 46" src="https://user-images.githubusercontent.com/1667598/55671812-39d25300-5894-11e9-96d2-c5231be5c21b.png">

**Comment by devCrossNet** [comment] 2019-04-06 16:01
fixed with commit: chore: https://github.com/vuesion/vuesion/commit/5b62057a52e6c0e626812154f92c077cf63a39ad

**Closed by devCrossNet** 2019-04-06 16:01 UTC
